version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "primeft/devops"
    commit-message:
      prefix: "chore(tooling)"
